---
# tasks file for sample_nodejs_app

- name: create app folder
  ansible.builtin.file: 
    path: "{{ hello_app_path }}"
    state: directory
    mode: '0755'
  register: app_folder

- name: copy app environment variables to .env folder
  template:
    src: templates/app_dotenv_config.j2
    dest: "{{ env_folder.path }}/.env"
    # owner: root
    # group: root
    mode: '0644'
  become: yes

- name: copy hello.js
  template:
    src: templates/hello.js.j2
    dest: "{{ app_folder.path }}/hello.js"
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: install pm2 package
  ansible.builtin.command: 
    cmd: "npm install pm2 -g"
    chdir: "{{ hello_app_path }}"
  become: yes

- name: install dotenv package
  ansible.builtin.command: 
    cmd: "npm install dotenv -g"
    chdir: "{{ hello_app_path }}"
  become: yes

- name: start nodejs app
  ansible.builtin.command: 
    cmd: "pm2 start hello.js -f"
    chdir: "{{ hello_app_path }}"
  become: yes

- name: restart nodejs app
  ansible.builtin.command: 
    cmd: "pm2 restart hello.js"
    chdir: "{{ hello_app_path }}"
