---
# tasks file for iptables
- name: Allow TCP 80 connections on INPUT chain
  ansible.builtin.iptables:
    protocol: tcp
    action: append
    chain: INPUT
    destination_port: 80
    ctstate: NEW,UNTRACKED
    match: tcp   
    jump: ACCEPT
    state: present        
  become: yes

- name: Allow TCP 443 connections on INPUT chain
  ansible.builtin.iptables:
    protocol: tcp
    action: append
    chain: INPUT
    destination_port: 443
    ctstate: NEW,UNTRACKED
    match: tcp   
    jump: ACCEPT
    state: present        
  become: yes

- name: Allow TCP connections on multiple ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    action: insert
    destination_ports:
      - "80"
      - "443"
    jump: ACCEPT
    state: present
  become: yes

- name: Allow connections on loopback interface
  ansible.builtin.iptables:
    chain: INPUT
    action: insert
    in_interface: lo
    jump: ACCEPT
    state: present
  become: yes

- name: Allow OUTPUT TCP connections on 443 port
  ansible.builtin.iptables:
    chain: OUTPUT
    protocol: tcp
    action: insert
    destination_ports:
      - "80"
      - "443"
    jump: ACCEPT
    state: present
  become: yes
