---
# file: main.yml


- name: Fetch all hosts to classify them
  hosts: all
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: "os_{{ ansible_facts['distribution'] + ansible_facts['distribution_major_version'] }}"
        
    # - name: Set OS distribution dependent variables
    #   ansible.builtin.include_vars: 
    #     dir: group_vars
    #     files_matching: "os_{{ ansible_facts['distribution'] + ansible_facts['distribution_major_version'] }}.yml"



- name: Install nginx with support to TLSv1.3 on Oracle Linux 8 
  hosts: os_OracleLinux8
  vars_files:
    - vars/default.yml
    - "vars/os_{{ ansible_facts['distribution'] + ansible_facts['distribution_major_version'] }}.yml"
  roles:
    - common
    - firewall-cmd
    - selinux
    - nginx
    # - sample_nodejs_app    
    - certbot
    - deploy-nodejs-git-app
    - validate

- name: Install nginx with support to TLSv1.3 on Ubuntu 20
  hosts: os_Ubuntu20
  vars_files:
    - vars/default.yml
    - "vars/os_{{ ansible_facts['distribution'] + ansible_facts['distribution_major_version'] }}.yml"
  roles:
    - common
    - iptables
    - nginx
    # - sample_nodejs_app
    - certbot
    - deploy-nodejs-git-app    
    - validate
        